package com.wilk.group.Project_web_admin;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
@Controller // This means that this class is a Controller

public class MainController {
//    @RequestMapping(path="/register")
//    public String register() {
//        return "html/register";
//    }
    @RequestMapping(path="/index")
    public String index() {
        return "html/index";
    }
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @RequestMapping(path="/register") // Map ONLY POST Requests
    public String addNewUser (@RequestParam("email") String email, @RequestParam("login") String login,
                              @RequestParam("password") String password) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setLogin(login);
        n.setPassword(password);
        n.setEmail(email);
        n.setPrivileges("user");
        userRepository.save(n);
        return "/html/index";
    }

//    @GetMapping(path="/results")
//    public @ResponseBody Iterable<User> getAllUsers() {
//        // This returns a JSON or XML with the users
//        return userRepository.findAll();
//    }
}