package com.wilk.group.Project_web_admin.controller;


import com.wilk.group.Project_web_admin.classes.User;
import com.wilk.group.Project_web_admin.classes.UserDto;
import com.wilk.group.Project_web_admin.repository.UserRepository;
import com.wilk.group.Project_web_admin.services.UserService;
import jakarta.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@Controller
public class authController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    private UserService userService;

    public authController(UserService userService) {
        this.userService = userService;
    }

    @GetMapping("index")
    public String index(){
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        if(authentication.isAuthenticated()) return "redirect:/panel";
        return "index";
    }

    @GetMapping("/login")
    public String login() {
        return "redirect:/panel";
    }
    @RequestMapping("/panel")
    public String panel(Model model){
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        String currentPrincipalName = authentication.getName();
        User user = new User();
        user = userService.findUserByEmail(currentPrincipalName);
        model.addAttribute("user", user);
        return "panel";
    }
    @GetMapping(path = "/register")
    public String register(Model model) {
        model.addAttribute("user", new UserDto());
        return "register";
    }
    @PostMapping(value = "/register/saveUser")
    public String saveUser(@Valid @ModelAttribute("user") UserDto newUser, BindingResult errors, Model model) throws Exception {
        User testLogin = userRepository.findByLogin(newUser.getLogin());
        User testEmail = userRepository.findByEmail(newUser.getEmail());
        if(testLogin != null && testLogin.getLogin() != null && !testLogin.getLogin().isEmpty()){
            errors.rejectValue("login", null,
                    "Istnieje konto o tym samym loginie");
        }
        if(testEmail != null && testEmail.getEmail() != null && !testEmail.getEmail().isEmpty()){
            errors.rejectValue("email", null,
                    "Istnieje konto o tym samym loginie");
        }
        if (errors.hasErrors()) {
            return "register";
        }else {
            userService.saveUser(newUser);
            return "redirect:/register?success";
        }
    }
    @GetMapping("/users")
    public String listRegisteredUsers(Model model){
        List<UserDto> users = userService.findAllUsers();
        model.addAttribute("users", users);
        return "users";
    }
}
